# Generated by Django 3.2.5 on 2021-07-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NominalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expected_sign', models.CharField(choices=[('dr', 'debit'), ('cr', 'credit')], max_length=2)),
                ('is_control_account', models.BooleanField()),
                ('is_bank_account', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amount_cumulative', models.IntegerField()),
                ('count_transactions', models.IntegerField()),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.nominalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='NominalTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True)),
                ('journal_id', models.IntegerField()),
                ('date_transaction', models.DateField()),
                ('period', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.nominalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('nominal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.nominalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('period', models.IntegerField()),
                ('lines', models.ManyToManyField(to='dashboards.JournalLine')),
            ],
        ),
    ]
