# Generated by Django 3.2.5 on 2021-07-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NominalTransactions",
            new_name="NominalTransaction",
        ),
    ]
